import { useEffect, useState } from "react";
import { INDEX_URL } from "../constants";
import type { VideoProject } from "../types";

type IndexState =
  | { status: "loading" }
  | { status: "error"; error: string }
  | { status: "ready"; projects: VideoProject[] };

/** Load the project catalogue generated by `npm run video:index`. */
export function useVideoIndex(): IndexState {
  const [state, setState] = useState<IndexState>({ status: "loading" });

  useEffect(() => {
    let cancelled = false;
    fetch(INDEX_URL, { cache: "no-cache" })
      .then(async (res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = (await res.json()) as { projects: VideoProject[] };
        if (!cancelled) setState({ status: "ready", projects: data.projects });
      })
      .catch((err) => {
        if (!cancelled) setState({ status: "error", error: err instanceof Error ? err.message : String(err) });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return state;
}
