import type { BayerSize } from './types'

/**
 * Bayer threshold matrices, generated by the standard recursion:
 *
 *   M(2n) = [ 4·M(n) + 0   4·M(n) + 2 ]
 *           [ 4·M(n) + 3   4·M(n) + 1 ]
 *
 * An ordered matrix rather than error diffusion (Floyd–Steinberg and friends)
 * because this runs per video frame: a Bayer lookup is a constant-time read per
 * pixel with no dependency on its neighbours, so it parallelises and — more
 * importantly here — a scrubbed frame always dithers to the same pixels rather
 * than shimmering as the error term propagates differently.
 *
 * Both backends read from here: the ink loop indexes the thresholds directly,
 * and the shader uploads these very values as a texture. This function is the
 * single source of truth for the pattern.
 */
export function bayerMatrix(size: BayerSize): Uint16Array {
  let matrix = Uint16Array.of(0, 2, 3, 1)
  let n = 2

  while (n < size) {
    const next = new Uint16Array(n * n * 4)
    const width = n * 2
    // Quadrant offsets, in the order top-left, top-right, bottom-left, bottom-right.
    const quadrant = [0, 2, 3, 1]

    for (let y = 0; y < n; y++) {
      for (let x = 0; x < n; x++) {
        const base = matrix[y * n + x] * 4
        next[y * width + x] = base + quadrant[0]
        next[y * width + (x + n)] = base + quadrant[1]
        next[(y + n) * width + x] = base + quadrant[2]
        next[(y + n) * width + (x + n)] = base + quadrant[3]
      }
    }

    matrix = next
    n = width
  }

  return matrix
}

const cache = new Map<BayerSize, Float32Array>()

/**
 * The matrix normalised to the open interval (-0.5, 0.5) — the form the ink loop
 * adds to luminance before testing against mid grey, and the form the shader
 * adds to pixel values. Cached: these are tiny, constant, and shared by every
 * instance on the page.
 */
export function bayerThresholds(size: BayerSize): Float32Array {
  const cached = cache.get(size)
  if (cached) return cached

  const matrix = bayerMatrix(size)
  const count = size * size
  const thresholds = new Float32Array(count)
  for (let i = 0; i < count; i++) {
    thresholds[i] = (matrix[i] + 0.5) / count - 0.5
  }

  cache.set(size, thresholds)
  return thresholds
}
